"""Add ON DELETE CASCADE to incident_updates.incident_id

Revision ID: c34f2d594e68
Revises: 
Create Date: 2025-06-13 20:29:53.231445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c34f2d594e68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_updates', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incident_updates', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incident_updates', 'incident_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('incident_updates_incident_id_fkey'), 'incident_updates', type_='foreignkey')
    op.create_foreign_key(None, 'incident_updates', 'org_incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.alter_column('org_incidents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('org_incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('org_incidents', 'status',
               existing_type=postgresql.ENUM('Ongoing', 'Resolved', name='orgincidentstatus'),
               nullable=False)
    op.alter_column('org_incidents', 'affected_services',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('org_incidents', 'org_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('org_incidents_org_slug_fkey'), 'org_incidents', type_='foreignkey')
    op.create_foreign_key(None, 'org_incidents', 'organizations', ['org_slug'], ['slug'], ondelete='CASCADE')
    op.alter_column('org_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('org_services', 'status',
               existing_type=postgresql.ENUM('Operational', 'Degraded', 'Partial', 'Major', name='orgservicestatus'),
               nullable=False)
    op.alter_column('org_services', 'org_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('org_services_org_slug_fkey'), 'org_services', type_='foreignkey')
    op.create_foreign_key(None, 'org_services', 'organizations', ['org_slug'], ['slug'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_services', type_='foreignkey')
    op.create_foreign_key(op.f('org_services_org_slug_fkey'), 'org_services', 'organizations', ['org_slug'], ['slug'])
    op.alter_column('org_services', 'org_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('org_services', 'status',
               existing_type=postgresql.ENUM('Operational', 'Degraded', 'Partial', 'Major', name='orgservicestatus'),
               nullable=True)
    op.alter_column('org_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'org_incidents', type_='foreignkey')
    op.create_foreign_key(op.f('org_incidents_org_slug_fkey'), 'org_incidents', 'organizations', ['org_slug'], ['slug'])
    op.alter_column('org_incidents', 'org_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('org_incidents', 'affected_services',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('org_incidents', 'status',
               existing_type=postgresql.ENUM('Ongoing', 'Resolved', name='orgincidentstatus'),
               nullable=True)
    op.alter_column('org_incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('org_incidents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'incident_updates', type_='foreignkey')
    op.create_foreign_key(op.f('incident_updates_incident_id_fkey'), 'incident_updates', 'org_incidents', ['incident_id'], ['id'])
    op.alter_column('incident_updates', 'incident_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incident_updates', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incident_updates', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
